name: Weekly LLM News Update

on:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil

      - name: Create update script
        run: |
          cat > update_readme.py << 'EOL'
          import os
          import json
          import re
          import requests
          from datetime import datetime
          from dateutil.relativedelta import relativedelta

          def search_brave(query, count=20):
              api_key = os.environ.get('BRAVE_API_KEY')
              headers = {'X-Subscription-Token': api_key}
              url = 'https://api.search.brave.com/res/v1/web/search'
              params = {
                  'q': query,
                  'count': count
              }
              response = requests.get(url, headers=headers, params=params)
              return response.json()

          def generate_readme_content(news_data):
              current_date = datetime.now().strftime("%B %d, %Y")
              
              content = f"""# LLM News Tracker

          A curated collection of the latest developments, breakthroughs, and news in the field of Large Language Models (LLMs).

          ## Latest Updates ({current_date})

          """

              # Add News Archives section
              content += "\n## News Archives\n\n"
              archive_links_md = "Browse news from previous weeks:\n\n"
              archive_files = []
              if os.path.exists('archives'):
                  archive_files = sorted(
                      [f for f in os.listdir('archives') if f.startswith('news_') and f.endswith('.md')],
                      reverse=True
                  )
              
              if archive_files:
                  for f_name in archive_files:
                      # Ensure correct path joining for markdown links
                      link_path = os.path.join('archives', f_name).replace('\\', '/')
                      date_str = f_name.replace('news_', '').replace('.md', '')
                      archive_links_md += f"- [News from {date_str}]({link_path})\n"
              else:
                  archive_links_md += "No archived news available yet.\n"
              
              content += archive_links_md
              
              # Process and categorize news here
              model_releases = []
              innovations = []
              market_trends = []
              
              # Categorize news based on content
              for item in news_data.get('web', {}).get('results', []):
                  title = item.get('title', '')
                  description = item.get('description', '')
                  url = item.get('url', '')
                  
                  # Simple categorization based on keywords
                  content_text = f"{title} {description}".lower()
                  
                  news_item = f"- **{title}**\n  - {description}\n  - [Source]({url})\n"
                  
                  if any(keyword in content_text for keyword in ['release', 'launch', 'version', 'model', 'gpt', 'claude', 'gemini']):
                      model_releases.append(news_item)
                  elif any(keyword in content_text for keyword in ['breakthrough', 'innovation', 'research', 'discover']):
                      innovations.append(news_item)
                  elif any(keyword in content_text for keyword in ['market', 'growth', 'trend', 'industry', 'adoption']):
                      market_trends.append(news_item)
              
              # Add model releases section
              if model_releases:
                  content += "\n### Major Model Releases & Improvements\n\n"
                  content += "\n".join(model_releases[:5])  # Limit to top 5
              
              # Add innovations section
              if innovations:
                  content += "\n### Notable Innovations\n\n"
                  content += "\n".join(innovations[:5])  # Limit to top 5
              
              # Add market trends section
              if market_trends:
                  content += "\n### Market Trends\n\n"
                  content += "\n".join(market_trends[:5])  # Limit to top 5
              
              # Add the standard sections
              content += """
          ## Contributing

          To contribute to this news tracker:

          1. Fork the repository
          2. Add your news item in the appropriate section
          3. Include:
             - Clear, concise summary
             - Date of announcement/development
             - Reliable source link
             - Any relevant technical details
          4. Submit a pull request

          ## News Categories

          - Model Releases
          - Research Breakthroughs
          - Industry Applications
          - Market Developments
          - Technical Innovations
          - Policy & Regulation
          - Open Source Developments

          ## Update Schedule

          This repository is updated weekly with the latest developments in the LLM space. Each update includes verification from multiple sources when available.

          ## Disclaimer

          The information provided in this repository is compiled from various sources and may not be comprehensive. Always refer to the original sources for complete details and verify information independently.

          ## License

          This repository is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.
          """
              
              return content

          def main():
              # Create archives directory if it doesn't exist
              os.makedirs('archives', exist_ok=True)

              # Archive existing README.md
              archive_date_str = None
              try:
                  with open('README.md', 'r', encoding='utf-8') as f_old:
                      old_content = f_old.read()
                  if old_content:
                      # Try to parse date from header like "## Latest Updates (May 19, 2025)"
                      match = re.search(r"## Latest Updates \((.+)\)", old_content)
                      if match:
                          parsed_date = datetime.strptime(match.group(1), "%B %d, %Y")
                          archive_date_str = parsed_date.strftime("%Y-%m-%d")
              except FileNotFoundError:
                  old_content = None # README.md doesn't exist
              
              if not archive_date_str: # Fallback if parsing failed or README was empty/not found
                  archive_date_str = (datetime.now() - relativedelta(weeks=1)).strftime("%Y-%m-%d")

              if old_content:
                  archive_filename = f"archives/news_{archive_date_str}.md"
                  with open(archive_filename, 'w', encoding='utf-8') as f_archive:
                      f_archive.write(old_content)
                  print(f"Archived old README to {archive_filename}")

              # Search for latest LLM news
              current_week_str = datetime.now().strftime("%Y-%m-%d")
              query = f"LLM AI language model news for week of {current_week_str}"
              news_data = search_brave(query)
              
              # Generate new README content
              new_content = generate_readme_content(news_data)
              
              # Write to README.md
              with open('README.md', 'w', encoding='utf-8') as f:
                  f.write(new_content)

          if __name__ == "__main__":
              main()
          EOL

      - name: Run update script
        env:
          BRAVE_API_KEY: ${{ secrets.BRAVE_API_KEY }}
        run: python update_readme.py

      - name: Commit and push if changes exist
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md archives/
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: update README with latest LLM news and archive old news [skip ci]" && git push)
